[Writable]
LogLevel = 'INFO'

[Service]
Host = "localhost"
Port = 59990
ConnectRetries = 20
Labels = []
OpenMsg = "REST device started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "RRS-Rapid-ElasticL-Q3I1D93JN2JQ-325700436.us-west-2.elb.amazonaws.com"
Port = 8500
Type = "consul"
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Protocol = "http"
  Host = "RRS-Rapid-ElasticL-Q3I1D93JN2JQ-325700436.us-west-2.elb.amazonaws.com"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Protocol = "http"
  Host = "RRS-Rapid-ElasticL-Q3I1D93JN2JQ-325700436.us-west-2.elb.amazonaws.com"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Protocol = "http"
  Host = "RRS-Rapid-ElasticL-Q3I1D93JN2JQ-325700436.us-west-2.elb.amazonaws.com"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

# Driver configs
[Driver]
Port = "8080"
Timeout = "5000"

[Logging]
EnableRemote = false
File = "./device-rest-go.log"

# Pre-define Devices
[[DeviceList]]
  Name = "device-pos-rest"
  Profile = "device-pos-rest"
  Description = "RESTful Device that sends in JSON POS data"
  Labels = [ "rest", "json", "pos" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
[[DeviceList]]
  Name = "device-roi-rest"
  Profile = "device-roi-rest"
  Description = "MQTT device for CV ROI events"
  Labels = [ "MQTT", "cv", "ROI"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = "tcp"
       Host = "localhost"
       Port = "1883"
       ClientId = "edgex-mqtt-roi-command-pub"
       User = ""
       Password = ""
       Topic = "EdgeXRoiCommand"
[[DeviceList]]
  Name = "device-scale-rest"
  Profile = "device-scale-rest"
  Description = "MQTT device for Scale"
  Labels = [ "MQTT", "scale"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = "tcp"
       Host = "RRS-Rapid-ElasticL-Q3I1D93JN2JQ-325700436.us-west-2.elb.amazonaws.com"
       Port = "1883"
       ClientId = "edgex-mqtt-scale-command-pub"
       User = ""
       Password = ""
       Topic = "EdgeXScaleCommand"
